name: Deploy Vercel
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: production or not
        id: prod_or_not
        run: |
          if [ "$REF" == 'refs/heads/main' ]
          then
              echo "::set-output name=vercel-args::--prod"
          else
              echo "::set-output name=vercel-args::"
          fi
        env:
          REF: ${{ github.ref }}
      - uses: amondnet/vercel-action@v25
        id: deploy-vercel
        if: github.event_name == 'push'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ steps.prod_or_not.outputs.vercel-args }}
          vercel-version: 29.1.1
